version: "3"
services:
  db:
    container_name: db_service
    image: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "utentiMicroservice"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    cap_add:
      - SYS_NICE
    expose:
      - 3307
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "./db_schema.sql:/docker-entrypoint-initdb.d/1.sql"
  exchange:
    container_name: exchange
    build: "./exchange"
    volumes:
      - "./proto:/src/proto"
    ports:
      - "9000:9000"
  users:
    container_name: users
    build: "./users"
    volumes:
      - "./proto:/src/proto"
    ports:
      - "9001:9001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - DB_URI=${DB_URI}
  api:
    container_name: api
    build: ./api
    volumes:
      - "./proto:/src/proto"
    ports:
      - "9002:9002"
    expose:
      - 9002
    depends_on:
      - exchange
      - users
      - db
  web:
    container_name: web
    build: ./web
    ports:
      - "5000:80"
    expose:
      - 5000
    depends_on:
      - exchange
      - users
      - db
      - api
  nginx:
    image: nginx:latest
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - exchange
      - users
      - db
      - api
      - web
