version: "3"
services:
  db:
    container_name: db_service
    image: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PORT: 3306
      MYSQL_DATABASE: "utentiMicroservice"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    cap_add:
      - SYS_NICE
    expose:
      - 3307
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - "./db_schema.sql:/docker-entrypoint-initdb.d/1.sql"
  exchange:
    container_name: exchange
    build: "./exchange"
    volumes:
      - "./proto:/src/proto"
    ports:
      - "9000:9000"
